[tool.poetry]
name = "nlp-ready"
version = "0.1.0"
description = ""
authors = ["arabidopsis <ian.castleden@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.6"
click = "^8.1.8"
requests = "^2.32.3"
lxml = "^5.3.0"
beautifulsoup4 = "^4.12.3"
selenium = "^4.27.1"
tabulate = "^0.9.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
