# Configuration
#
# Name of current project

# NAME = 'suba'
# NAME = 'cropPAL'
NAME = 'cropTiPS'

# Where to put the downloaded xml/html files

# DATADIR = '../suba/'
# DATADIR = '../croppal/'
DATADIR = '../croptips/'

# file generated by `python3 issn.py journals [csvfile]`
# we need an input a CSV of pubmed IDs
# that we are interested in.
# This finds ISSN of journal and DOI/PMCID of paper
# by scraping NCBI website.

# JCSV = '../csv/suba-journals.csv'
# JCSV = '../csv/croppal-journals.csv'
JCSV = '../csv/croptips-journals.csv'

# for `python3 issn.py tohtml`
# saves state so we can reproduce html
# on a per module basis

# PKLFILE = DATADIR + 'subamap.pkl'
# PKLFILE = DATADIR + 'croppalmap.pkl'
PKLFILE = DATADIR + 'croptips.pkl'
