# Configuration
#
# Name of current project
# only used for html output
NAME = "cropTiPS"

# Where to put the downloaded xml/html files
# ** need '/' at end! **.
DATADIR = "croptips/"

# file generated by `python3 -m mlcode journals [csvfile]`
# we need an input a CSV of pubmed IDs
# that we are interested in.
# This finds ISSN of journal and DOI/PMCID of paper
# by scraping NCBI website.
JCSV = "csv/croptips-journals.csv"

# for `python3 -m mlcode tohtml --cache={PKLFILE}`
# saves state so we can reproduce html
# on a per module basis
PKLFILE = DATADIR + "croptips.pkl"
