# configuration
#
# where to put the downloaded xml/html files
DATADIR = '../croppal/'
# file generated by issn.py journals
# we need an input a CSV of pubmed IDs
# that we are interested in.
# this finds ISSN of journal and DOI/PMCID of paper
# from NCBI
JCSV = '../csv/croppal-journals.csv'
# for issn.py tohtml
# saves state so we can reproduce html
# on a per module basis
PKLFILE = '../csv/croppalmap.pkl'
