# Configuration
#
# Name of current project
# only used for html output
from __future__ import annotations

NAME = "nlpready"

# Where to put the downloaded xml/html files
DATADIR = "nlpready-data"

# file generated by `python3 -m nlpready journals [csvfile]`
# we need an input a CSV of pubmed IDs
# that we are interested in.
# This finds ISSN of journal and DOI/PMCID of paper
# by scraping NCBI website.
JCSV = "nlpready-journals.csv"

# for `python -m nlpready tohtml --cache={PKLFILE}`
# saves state so we can reproduce html
# on a per module basis
PKLFILE = "nlpready.pkl"
