# Configuration
#
# Name of current project
# only used for html output
from __future__ import annotations


# Where to put the downloaded xml/html files
DATADIR = "scifeeder-data"

# file generated by `python3 -m scifeeder make-papers [csvfile]`
# we need an input a CSV of pubmed IDs
# that we are interested in.
# This finds ISSN of journal and DOI/PMCID of paper
# by scraping NCBI website.
JCSV = "scifeeder-papers.csv"


USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.140 Safari/537.36"
